"""create tables

Revision ID: 4f0cbf2372bf
Revises: 
Create Date: 2024-12-13 12:01:10.739422+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '4f0cbf2372bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i2v_task',
    sa.Column('source_image_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'PROMPT_GENERATED', 'TASK_SUBMITTED', 'TASK_COMPLETED', 'FAILED', name='taskstatus', native_enum=False), nullable=False),
    sa.Column('i2v_type', sa.Enum('IMAGINATIVE', 'REALISTIC', name='i2vtype', native_enum=False), nullable=False),
    sa.Column('video_generation_provider', sa.Text(), nullable=False),
    sa.Column('video_generation_prompt', sa.Text(), nullable=False),
    sa.Column('video_generation_id', sa.Text(), nullable=False),
    sa.Column('output_video_filename', sa.String(length=255), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('i2v_task')
    # ### end Alembic commands ###
