"""allow_null_video_generation_prompt

Revision ID: 835378594b89
Revises: 4f0cbf2372bf
Create Date: 2024-12-13 12:39:55.848633+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '835378594b89'
down_revision: Union[str, None] = '4f0cbf2372bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('i2v_task', 'video_generation_prompt',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('i2v_task', 'video_generation_id',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('i2v_task', 'output_video_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('i2v_task', 'output_video_filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('i2v_task', 'video_generation_id',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('i2v_task', 'video_generation_prompt',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
