version: '3.8'

services:
  web:
    build: .
    container_name: service-web
    ports:
      - "8080:80"
    volumes:
      - ./app:/app-instance
    environment:
      - PYTHONUNBUFFERED=1
      - ENV_FILE=/code/videosnap-dev.env